config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  get 'pages/home'

  get '/pizza', to: 'pages#pizza'

  get '/appetizers', to: 'pages#appetizers'

  get  '/calzones', to: 'pages#calzones'
  
  get  '/desserts', to: 'pages#desserts'

  get '/subs', to: 'pages#subs'
  
  get '/specials', to: 'pages#specials'

  get 'home/pizza'

  get 'home/appetizers'

  get 'home/subs'
  
  get 'pages/test', as: 'test'
  
  get 'menus/full_menu', as: 'full_menu'
  get 'menus/switch_store/:store', to: 'menus#switch_store', as: 'switch_store'
  
  get 'stores/enter_zip', as: 'enter_zip'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
  CLAYTON_STORE_MAPS_LINK = "https://maps.google.com/maps?ll=35.664466,-78.210854&z=10&t=m&hl=en&gl=US&mapclient=embed&q=50%20Neuse%20River%20Pkwy%2C%20Suite%209%20clayton%2C%20nc"
  CLAYTON_STORE = [35.649363, -78.394231]
  DURHAM_STORE = [35.994033, -78.898619]
  DURHAM_STORE_MAPS_LINK ="https://www.google.com/maps/place/121+Sherron+Rd+%23301,+Durham,+NC+27703/@35.9742248,-78.7952097,17z/data=!4m2!3m1!1s0x89acfba0082e1a59:0xe0e153ed31923837"
  
  def self.closer_store_by_zip zip
    geo = Geocoder.search(zip.to_s)
    if geo and geo.first
      geo = geo.first.coordinates
      return self.closer(geo.first, geo.last)
    end
  end

  def self.closer_store ip
    geoip = GeoIP.new('GeoLiteCity.dat').city(ip.to_s)
    if defined? geoip and geoip
      return self.closer(geoip.latitude, geoip.longitude)
    end
  end
  
  def self.closer latitude, longitude
    store1 = Store::CLAYTON_STORE
    store2 = Store::DURHAM_STORE
    if latitude and longitude
      current = [latitude, longitude]
      if GeoDistance::Haversine.distance(current[0], current[1], store1[0], store1[1]).miles.number > \
        GeoDistance::Haversine.distance(current[0], current[1], store2[0], store2[1]).miles.number
        return :durham
      else
        return :clayton
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :closer_store

  def closer_store
    if cookies[:closer_store_by_zip]
      return cookies[:closer_store_by_zip].to_sym
    else
      return Store.closer_store(request.remote_ip)
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def full_menu
    pdf_filename = File.join(Rails.root, "app/assets/images/menus/full_menu.pdf")
    send_file(pdf_filename, filename: "full_menu.pdf", disposition: "inline", type: "application/pdf")
  end
  
  def switch_store
    if params[:store].eql? :clayton.to_s
      @clayton = true
    elsif params[:store].eql? :durham.to_s
      @durham = true
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def pizza
  end

  def appetizers
  end

  def calzones
  end

  def subs
  end
  
  def dessert
  end
  
  def specials
  end
  
  def test
    
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def enter_zip
    cookies.permanent[:closer_store_by_zip] = Store.closer_store_by_zip(params[:zip])
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Romas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  
  <%= render "shared/plugins" %>

  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
</head>

<body class="site">
	<%= render "shared/header" %>
	<div id="nav_anchor"></div>
	<%= render "shared/nav" %>
	<%= render "shared/phone" %>
	<div class="container">
		<div class="content">
	    <%= yield %>
    </div>
	</div>

	<div class= "container">
	  <%= render "shared/footer" %>
  </div>
</body>
</html>

app/views/menus/switch_store.js.erb
$("#main_nav_container").remove();
$("#nav_anchor").after("<%= render 'shared/nav', clayton: @clayton, durham: @durham %>")

app/views/pages/appetizers.html.erb
<center><div class="page-header modHeader">
  <h1 class="underline">Appetizers  Wings  Salads</h1>
</div>
</center>
<div >
<%= image_tag "app.jpg", :class=> "menue"%>
</div>

app/views/pages/calzones.html.erb
<center><div class="page-header modHeader">
  <h1 class="underline">Calzones & Pastas</h1>
</div>
</center>
<div >
<%= image_tag "pasta.jpg", :class=> "menue"%>
</div>

app/views/pages/desserts.html.erb
<center><div class="page-header modHeader">
  <h1 class="underline">Desserts</h1>
</div>
</center>
<div >
<%= image_tag "desserts.jpg", :class=> "menue"%>
</div>

app/views/pages/home.html.erb
<h1>Welcome to Roma Pizza Shop</h1>
<div>
	<%=image_tag"ingredients.jpg", :class=> "ImageLeftWrap"%>
	<h2>Pizza you can write home about</h2>
	<p>The magic of Roma Pizza Shop is our use of

	fresh ingredients and spices that keep our

	customers coming back for more. Every dish

	we prepare is made to order, and is baked

	with care and quality with its own distinctive

	flavor and aroma.</p>
	<p>
  <%= link_to "Click Here", full_menu_path %>
	for our full Menu.
	<br>
	</p>
</div>
<div>
	<h2>Always fresh </h2>
	<p>We use fresh spices and herbs for each individual dish and blend our own unique taste of spices and herbs that makes Roma pizza one of a kind.</br>


At Roma Pizza Shop, we strive to always bring you a little more… more delicious ways to discover great food, and more smiles and service from our enthusiastic team of pizza connoisseurs. Honest home style cooking is our obsession that we can't help. We go out of our way to bring you tasty flavors and fresh dishes that keep you craving another bite at Roma Pizza Shop.</p>
</div>

<div>
	<h2> Call today for delivery!</h2>
	<p>Smart humble service with infectious ambiance and a fresh vibe, creates an environment where you and your friends can feel at home, relax and be free. Call us today to order your own Roma Pizza creation!</p>
</div>
<div class="map">
	<div id="map-canvas" class="map"></div>
	<div class="map1" jstcache="128">
	<a class="google-maps-link" href="https://maps.google.com/maps?ll=35.664466,-78.210854&z=10&t=m&hl=en&gl=US&mapclient=embed&q=50%20Neuse%20River%20Pkwy%2C%20Suite%209%20clayton%2C%20nc" jstcache="2" jsaction="mouseup:placeCard.largerMap" target="_blank">View larger map</a>
	</div>
</div>

app/views/pages/pizza.html.erb
<center><div class="page-header modHeader">
  <h1 class="underline">Pizzas</h1>
</div>
</center>
<div >
<%= image_tag "pizza.jpg", :class=> "menue"%>
</div>

app/views/pages/specials.html.erb
<center><div class="page-header modHeader">
  <h1 class="underline">Specials</h1>
</div>
</center>
<div >
<%= image_tag "specials.jpg", :class=> "menue"%>
</div>

app/views/pages/subs.html.erb
<center><div class="page-header modHeader">
  <h1 class="underline">Subs</h1>
</div>
</center>
<div >
<%= image_tag "subs.jpg", :class=> "menue"%>
</div>

app/views/pages/test.html.erb
<%= link_to "this fucking button", "#", id:"someId" %>
<h1 id="myId">This fucking works</h1>
<h1>some stuff</h1>

app/views/shared/_footer.html.erb
	<div class= "textwhite">
	<h4>Copyright &copy; Roma Pizza Shop, 2012. All rights reserved.</h4>
	</div>
	<div class="floatl">
	<div class="fb-like" data-href="http://www.romapizzashopnc.com/" data-width="100" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
	</div>
	<div class="floatl">
	<a href="https://twitter.com/share" class="twitter-share-button" data-dnt="true">Tweet</a>
	
	</div>
	<div class= "floatl">
	
	<g:plus action="share" annotation="bubble"></g:plus>
	</div>

app/views/shared/_header.html.erb
<div class="container" style="position: relative">
  	<%= image_tag "header2.jpg", :class=>"pic1" %>
</div>

app/views/shared/_nav.html.erb
<div class="container" id="main_nav_container" style="font-size: 115%">
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header" style="vertical-align: middle; horizontal-align: middel;">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href=<%=root_path%>>Roma</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li ><a href=<%=pizza_path%>>Pizza <span class="sr-only">(current)</span></a></li>
	        <li><a href=<%=appetizers_path%>>Appetizers</br>Wings & Salads</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Deserts <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href=<%=desserts_path%>>Desserts</a></li>
	            <li><%= link_to "Full Menu", full_menu_path %></li>
	            <!--<li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>-->
	          </ul>
	        </li>
			<li><a href=<%=calzones_path%>>Calzones </br>Pasta</a></li>
			<li><a href=<%=subs_path%>>Subs</a></li>
			<li><a href=<%=specials_path%>>Specials</a></li>
			<li><%= link_to "Full Menu", full_menu_path %></li>
	      </ul>

	      <ul class="nav navbar-nav navbar-right">
	        
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= closer_store.eql?(:durham) ? "Store" : "Store" %><span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li>
	             <a href="<%= Store::CLAYTON_STORE_MAPS_LINK %>">
	              Clayton (919) 550-7070
				  <br/>
				   <%= link_to "Clayton Order Online", "https://ordering.bigholler.com/RomaPizzaShopClayton"%>
					    </a>
					  </li>
	            <li role="separator" class="divider"></li>
	           <li>
  	             <a href="<%= Store::DURHAM_STORE_MAPS_LINK %>">
  	              Durham (919)957-7662 <br/>
				  <%= link_to "Durham Order Online", "https://ordering.bigholler.com/RomaPizzaShop/" %>
  					    </a>
				   <!--<%= link_to "Store in Durham, NC 27701", switch_store_path(:durham), remote: true %>--></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
</div>

app/views/shared/_phone.html.erb
<div class="container phoneNum">
	<%= link_to "Clayton Order Now", "#",class: "btn btn-primary", id: "cla-link" %>
	<h1 id="phone-cla">(919)550-7070 <%= link_to "Clayton Order Online", "https://slicelife.com/restaurants/nc/clayton/27527/roma-pizza-shop-clayton/menu?"%></h1>
	
	</br>
	<%= link_to "Durham Order Now", "#", class: "btn btn-primary",id: "dum-link" %>
	<h1 id="phone-dum">(919)957-7662 <%= link_to "Durham Order Online", "https://slicelife.com/restaurants/nc/durham/27703/roma-pizza-shop/menu?" %></h1>
	
	
</div>

app/views/shared/_plugins.html.erb
<script src="https://maps.googleapis.com/maps/api/js" ></script>
<script>
  function initialize() {
	
	var myLatlng = new google.maps.LatLng(35.6502, -78.3943);
	var mapOptions = {
	    zoom: 16,
	    center: myLatlng
	}
	var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
	var marker = new google.maps.Marker({
	      position: myLatlng,
	      map: map,
	      title: 'Roma Pizza Shop'
	  });
	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>
  
<div id="fb-root"></div>
<!-- facebook like/share sdk -->
<script>
	(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
		fjs.parentNode.insertBefore(js, fjs);
	} (document, 'script', 'facebook-jssdk'));
</script>
<script src="https://apis.google.com/js/plusone.js"></script>
<script>
	!function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0],
			p = /^http:/.test(d.location) ? 'http' : 'https';
		if (!d.getElementById(id)) {
			js = d.createElement(s);
			js.id = id;
			js.src = p + '://platform.twitter.com/widgets.js';
			fjs.parentNode.insertBefore(js, fjs);
		}
	}(document, 'script', 'twitter-wjs');
</script>

app/views/stores/_enter_zip.html.erb
<!-- stores -->

<%= form_tag enter_zip_path, method: :get do |f| %>
	<%= text_field_tag :zip, nil, placeholder: "Enter your zip code here" %>
	<%= submit_tag "Enter" %>
<% end %>